"""initial migration

Revision ID: dbf34224ee95
Revises: 
Create Date: 2025-03-04 23:33:32.497465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf34224ee95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_eng', sa.String(), nullable=False),
    sa.Column('title_uzb', sa.String(), nullable=False),
    sa.Column('title_rus', sa.String(), nullable=False),
    sa.Column('description_eng', sa.String(), nullable=False),
    sa.Column('description_uzb', sa.String(), nullable=False),
    sa.Column('description_rus', sa.String(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('eng', sa.String(), nullable=False),
    sa.Column('uzb', sa.String(), nullable=False),
    sa.Column('rus', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_eng', sa.String(), nullable=False),
    sa.Column('title_uzb', sa.String(), nullable=False),
    sa.Column('title_rus', sa.String(), nullable=False),
    sa.Column('description_eng', sa.String(), nullable=False),
    sa.Column('description_uzb', sa.String(), nullable=False),
    sa.Column('description_rus', sa.String(), nullable=False),
    sa.Column('typee', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('gramm', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('product')
    op.drop_table('language')
    op.drop_table('gift')
    # ### end Alembic commands ###
